---
extends: eslint:recommended
env:
  browser: true
  jquery: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  quotes:
    - 2
    - single
  semi: 2
  no-unused-vars: 0
  no-console: 0
